// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbS2c-kDQPsi2AJFawE3pQukjVFowWlU',
    appId: '1:330864987458:web:945c97d4f1d07dee6fccdb',
    messagingSenderId: '330864987458',
    projectId: 'my-coool',
    authDomain: 'my-coool.firebaseapp.com',
    storageBucket: 'my-coool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3UCvkqAq95Qk7nY4dPPEmhJuOe8_qgQ',
    appId: '1:330864987458:android:cb135cfd09e43a406fccdb',
    messagingSenderId: '330864987458',
    projectId: 'my-coool',
    storageBucket: 'my-coool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmyt6VWgPtqnv0GWj8l8z0Js28uO9Wjs',
    appId: '1:330864987458:ios:e19867dcfae28e776fccdb',
    messagingSenderId: '330864987458',
    projectId: 'my-coool',
    storageBucket: 'my-coool.firebasestorage.app',
    iosBundleId: 'com.example.facebookclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmyt6VWgPtqnv0GWj8l8z0Js28uO9Wjs',
    appId: '1:330864987458:ios:e19867dcfae28e776fccdb',
    messagingSenderId: '330864987458',
    projectId: 'my-coool',
    storageBucket: 'my-coool.firebasestorage.app',
    iosBundleId: 'com.example.facebookclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbS2c-kDQPsi2AJFawE3pQukjVFowWlU',
    appId: '1:330864987458:web:170ad015432135d66fccdb',
    messagingSenderId: '330864987458',
    projectId: 'my-coool',
    authDomain: 'my-coool.firebaseapp.com',
    storageBucket: 'my-coool.firebasestorage.app',
  );
}
